sudo: false
dist: "trusty"
language: python
cache: pip
python:
    - "3.6"
addons:
  apt:
    packages:
    - "python3-pip"
    - "google-chrome-stable"
    - "libev-dev"
branches:
  only:
    - master

before_install:
- pip3 install -r requirements.txt
- wget http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
- mkdir chromedriver
- unzip chromedriver_linux64.zip -d chromedriver/
- export PATH=$PATH:$PWD/chromedriver
before_script:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1366x768x16"
script:
- pytest test_ui/tests
